CurrentPort: 7000
PlayerServerDirectory: '/root/Cerulean/servers/%PLAYER/server.properties'
BungeeConfigLocation: '/root/Cerulean/Bungee/config.yml'
ScriptsDirectory: '/root/Cerulean/Scripts/'
ActivePlayers: